#!/bin/python3

import sys
import json
import loca
import re
from pathlib import Path
from eprint import eprint

def transform(name, x, y, z):
    if name == 'Rogue.obj':
        return [x *  0.22534781079120067 +  623.9358100432041,
                y * -0.22453135841922706 - 1059.4875167327712]
    return [x *  0.33953260812857690150522441401203 +  620.65061007976712362166120182265,
            y * -0.33837323271747048290964894533602 - 1056.58417176272120743560261062940]

def capitalize(matchobj):
    return matchobj.group(1).capitalize()

nodes = json.load(open('nodes.json', 'r'))
systems = loca.load(open('systems.loca.json', 'r'))
factions = loca.load(open('factions.loca.json', 'r'), trimPrefix='faction')
resources = loca.load(open('resources.loca.json', 'r'), trimPrefix='resource')
galaxy = nodes['galaxy_optimised']
coords = {}

obj = {
    'type': 'FeatureCollection',
    'features': []
}

#############
#           #
#   NODES   #
#           #
#############

gb = [[None, None], [None, None]]
for i in range(0, len(galaxy['node_ids'])):
    x = galaxy['x_coords'][i]
    y = galaxy['y_coords'][i]
    gb[0][0] = x if gb[0][0] is None else min(gb[0][0], x)
    gb[0][1] = y if gb[0][1] is None else min(gb[0][1], y)
    gb[1][0] = x if gb[1][0] is None else max(gb[1][0], x)
    gb[1][1] = y if gb[1][1] is None else max(gb[1][1], y)
    node = str(galaxy['node_ids'][i]) 
    fid = str(galaxy['factions'][i])
    if fid not in factions.data and fid != "-1":
        eprint(f"WARNING: Faction {fid} not found in factions loca")
    obj['features'].append({
        'type': 'Feature',
        'properties': {
            'objectid':             node,
            'name':                 systems.data.get(node, {'title': 'Unknown'})['title'],
            'level':                galaxy['levels'][i],
            'faction':              factions.data.get(fid, {'name': 'Independent'})['name'],
            'miningSetups':         galaxy['mining_setups'][i],
            'isDeepSpace':          galaxy['is_deep_space'][i],
            'marauderSpawnRuleIds': galaxy['marauder_spawn_rule_ids'][i],
        },
        'geometry': {
            'type': 'Point',
            'coordinates': [x, y],
        },
    })
    coords[node] = [x, y]
eprint(f"Galaxy bounds: ({gb[0][0]}, {gb[0][1]})-({gb[1][0]}, {gb[1][1]})")

#############
#           #
#   PATHS   #
#           #
#############

# Paths are directional, that means for every connection the path will be
# represented twice. This is undesirable as a waste of resources, but also
# because we want to be able to style special warp paths (like toll roads)
# and we can't do that if we draw another line directly above/below it.

path_map = {}
# First, add all the toll roads
for i in range(0, len(galaxy['source_ids'])):
    if galaxy['unlock_req_count'][i] < 1:
        continue
    sys1 = str(galaxy['source_ids'][i])
    sys2 = str(galaxy['dest_ids'][i])
    # Enforce a guaranteed order so we can find the path the other way
    if sys1 < sys2:
        sys1, sys2 = sys2, sys1
    k = f"{sys1}-{sys2}"
    path_map[k] = i
# Next, add the remaining paths if they're not already drawn
for i in range(0, len(galaxy['source_ids'])):
    sys1 = str(galaxy['source_ids'][i])
    sys2 = str(galaxy['dest_ids'][i])
    if sys1 < sys2:
        sys1, sys2 = sys2, sys1
    k = f"{sys1}-{sys2}"
    if k in path_map:
        continue
    path_map[k] = i

# Now produce our output using only single paths
counts = {
    '0': 'None',
    '1': 'Toll',
    '2': 'Recall',
}
types  = {
    '0': 'Empty',
    '1': 'None',
    '2': 'Mission',
    '3': 'Resource',
}
default_res = {
    'description': 'Unknown',
    'name': 'Unknown',
    'nameShort': 'Unknown',
}
for i in path_map.values():
    feature = {
        'type': 'Feature',
        'properties': {
            'source':   systems.data.get(str(galaxy['source_ids'][i]), {'title': 'Unknown'})['title'],
            'dest':     systems.data.get(str(galaxy['dest_ids'][i]), {'title': 'Unknown'})['title'],
            'distance': galaxy['distances'][i],
        },
        'geometry': {
            'type': 'LineString',
            'coordinates': [
                coords[str(galaxy['source_ids'][i])],
                coords[str(galaxy['dest_ids'][i])],
            ],
        },
    }
    count = galaxy['unlock_req_count'][i]
    if count > 0:
        req_id = galaxy['unlock_offset'][i]
        source = str(galaxy['unlock_req_sources'][req_id])
        toll = {
            'class':    counts.get(str(count)),
            'type':     types.get(str(galaxy['unlock_req_types'][req_id])),
            'quantity': galaxy['unlock_req_quantities'][req_id],
        }
        if toll['type'] == 'Resource':
            toll['resource'] = resources.data.get(source, default_res)
            toll['resource']['id'] = source
        else:
            toll['mission'] = source
        feature['properties']['toll'] = toll
    obj['features'].append(feature)

##############
#            #
#   MESHES   #
#            #
##############

# We should figure out a way to merge each group of faces into a single poly.
# Currently we are just rendering every single face on its own, another waste
# of resources.

colors = {
    'Federation.obj': '#0080ff',
    'Romulan.obj':    '#00ff00',
    'Klingon.obj':    '#ff0000',
    'Augment.obj':    '#ffbb00',
    'Rogue.obj':      '#ff00ff',
    'Dominion.obj':   '#8000ff',
}
start = len(obj['features'])
p = Path('obj')
for fo in p.glob('*.obj'):
    eprint(f"Working on {fo}")
    vertices = [(0, 0, 0)]  # OBJ files are 1-indexed, insert a dummy element
    mb = [[None, None], [None, None]]
    with fo.open('r') as f:
        for line in f:
            match = re.match(r'v ([-0-9eE.]+) ([-0-9eE.]+) ([-0-9eE.]+)', line)
            if not match:
                continue
            (x, z, y) = [float(v) for v in match.groups()]
            vertices.append(transform(fo.name, x, y, z))
            mb[0][0] = x if mb[0][0] is None else min(mb[0][0], x)
            mb[0][1] = y if mb[0][1] is None else min(mb[0][1], y)
            mb[1][0] = x if mb[1][0] is None else max(mb[1][0], x)
            mb[1][1] = y if mb[1][1] is None else max(mb[1][1], y)
    eprint(f"Found {len(vertices)} vertices")
    with fo.open('r') as f:
        for line in f:
            match = re.match(r'f (\d+)/\d+/\d+ (\d+)/\d+/\d+ (\d+)/\d+/\d+', line)
            if not match:
                continue
            indices = [int(v) for v in match.groups()]
            feature = {
                'type': 'Feature',
                'properties': {
                    'color': colors.get(fo.name, '#ff0000'),
                },
                'geometry': {
                    'type': 'Polygon',
                    'coordinates': [[
                        vertices[indices[0]],
                        vertices[indices[1]],
                        vertices[indices[2]],
                        vertices[indices[0]],
                    ]],
                },
            }
            obj['features'].append(feature)
        eprint(f"Found {len(obj['features']) - start} faces")
    eprint(f"Mesh bounds: ({mb[0][0]}, {mb[0][1]})-({mb[1][0]}, {mb[1][1]})")

scale_x = float(gb[1][0] - gb[0][0]) / (mb[1][0] - mb[0][0])
scale_y = float(gb[1][1] - gb[0][1]) / (mb[1][1] - mb[0][1])
eprint(f"Scale: ({scale_x}, {scale_y})")

json.dump(obj, fp=sys.stdout, indent=2)
print()
